### PR TITLE
add synid for storage project

### PR DESCRIPTION
**Pull request by kelshmo**
I made a new project for storing this output only accessible to the curation team!

### CODE REVIEW

**Comment by Aryllen** [comment]
Great! I do have one suggestion. Since dccmonitor becomes less helpful when "old" validation files are laying around, the AMP-AD group has moved to this format for the validation project.
image
dccvalidator points to the Active folder and uploads files there. dccmonitor collects files from the Active folder. I have the storage of annotations set for the dccmonitor folder. Finally, the Archived folder is where validated files are moved to once the data for those has been released. This setup allows for keeping all of the files related to metadata validation in one place.

I know you've already created a project for the dccmonitor uploads. However, if you want to switch to this format, you could update this PR request with the new synIds for the Active and dccmonitor folders. However, if you are happy with the separate projects, I can go ahead and merge this PR. Just let me know.

**Comment by kelshmo** [comment]
Can you send me the synID of this project?

**Comment by kelshmo** [comment]
I like this model because everything is in one place. I will update my PR accordingly!

**Comment by Aryllen** [comment]
Great! I noticed that you made the Active folder, as well. There's a couple more steps.
1. Move the individual user folders from the original parent folder into Active.
2. Update the scope of the fileview to be files within Active.

If we upload annotations to the dccmonitor folder that was created without updating the fileview to a new scope, dccmonitor will have issues when running.

If you need any help moving the individual folders over to Active, I can help with that.

**Comment by kelshmo** [comment]
I've implemented those changes - thank you.

**Pull request merged**
